import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FirebaseAuthProvider, useFirebaseAuth } from "@/config/AuthContext";
import { fetchMostRecentEventImage } from "@/utils/getEvents";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Outdoor Education Center",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lcpImageUrl = await fetchMostRecentEventImage();

  return (
    <html lang="en">
      <FirebaseAuthProvider >
      <head>
        <link rel="icon" href="/images/icon.ico"></link>
        {lcpImageUrl && (
          <link 
          rel="preload" 
          as="image" 
          href={lcpImageUrl}
          type="image/webp" 
          fetchPriority="high"
        />
        )}
        
      </head>
        <body className={inter.className}>{children}</body>
      </FirebaseAuthProvider>
    </html>
  );
}
