import type { Metadata } from "next";
import { AR_One_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/config/AuthContext";
import { ProfileProvider } from "@/config/ProfileContext";

const AROneSans = AR_One_Sans({
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Outdoor Education Center",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ProfileProvider>
          <head>
            <link rel="icon" href="/images/icon.ico"></link>
          </head>
          <body className={AROneSans.className}>{children}</body>
        </ProfileProvider>
      </AuthProvider>
    </html>
  );
}
